### ISSUE TITLE
strategic partnerships wrong taxid

### ISSUE THREAD

**Issue by andrasvereckei** [ceumicrodata/firms#16]
The strategic partnerships tax_ids updated in tool spreadsheet: 

https://docs.google.com/spreadsheets/d/1gsajrt_V-6rZxAoqD62O6H_y0ZDVVSwkPKGT99bBqHM/edit?gid=1917662552#gid=1917662552

https://github.com/ceumicrodata/firms/blob/9f2b6df1fceaac588b25e04520cce1cff6c728f8/src/consts.jl#L6

The ChatGPT results are wrong.

**Comment by korenmiklos** [comment]
yes, i realized it made up the mumbers.

**Comment by andrasvereckei** [comment]
Updated on my branch: 
https://github.com/ceumicrodata/firms/blob/figures_update/src/consts.jl
