### ISSUE TITLE
Before collapse, redefine category

### ISSUE THREAD

**Issue by korenmiklos** [ceumicrodata/firms#27]
https://github.com/ceumicrodata/firms/blob/4575bf1ad840298233fe0993a2d9d23aa6364f03/src/functions.jl#L95

```julia
@replace category = size_category(max_emp_5)
```

so that categories are fixed over time

**Comment by andrasvereckei** [comment]
> https://github.com/ceumicrodata/firms/blob/4575bf1ad840298233fe0993a2d9d23aa6364f03/src/functions.jl#L95
> 
> ```julia
> @replace category = size_category(max_emp_5)
> ```
> 
> so that categories are fixed over time

This will give you back only micro, small, medium and large categories from size_category function.

   category |      Freq.     
------------+--------
large       |      46,206       
medium |    172,541       
micro      |  9,016,201   
small      |    960,436    
------------+----------
      Total | 10,195,384     


Lost foreign category and labels. 
Looking for solution.

**Comment by korenmiklos** [comment]
You can add 
replace category = "foreign" if foreign
after the category has been redefined.
