### ISSUE TITLE
fig 2 sales per worker by category

### ISSUE THREAD

**Issue by andrasvereckei** [ceumicrodata/firms#3]
Sales per worker by categories 
- Categories are in #2 
```
@collapse sum_sales = sum(sales) sum_emp = sum(emp), by(year kateg); 
@generate sales_per_emp = sum_sales / sum_emp

- Test the diff. with sales_clean. Emp already cleaned. 
@collapse sum_sales_clean = sum(sales_clean) sum_emp = sum(emp), by(year kateg);
@generate sales_per_emp = sum_sales_clean / sum_emp

- Do it with deflated sales
@collapse sum_sales21 = sum(sales21) sum_emp = sum(emp), by(year kateg); 
@generate sales_per_emp = sum_sales21 / sum_emp
```

- Drop so3 and or micro ventures if too small. 
- Must need small, medium, big firms. 
- Separately for foreign and domestic

"Egy főre jutó árbevétel, kategóriák szerint
mindkét változó tisztítva
sales PPI-vel deflálva
ha kell, kisebb csoportok eldobhatók
so3 elhagyható, ha nem jelentős
mikro és kis összevonható
de minimum maradjon: kis, közép, nagy és fo3
"

**Comment by andrasvereckei** [comment]
https://github.com/ceumicrodata/firms/blob/figures_update/output/fig/sales_per_worker.png

**Comment by korenmiklos** [comment]
Annotate:
- large purchase by GE in 2015
