### ISSUE TITLE
fig 3 gdp per worker by categories

### ISSUE THREAD

**Issue by andrasvereckei** [ceumicrodata/firms#4]
Gdp per worker by categories #2 
- Use gdp not gdp2
- Maybe gdp21 deflated is better to use.

"Egy főre jutó hozzáadott érték, kategóriák szerint
gdp1, gdp2"

**Comment by korenmiklos** [comment]
See https://github.com/ceumicrodata/firms/blob/main/output/fig/gdp_per_worker.png

**Comment by korenmiklos** [comment]
Annotate:
- 2015, GE sales jump
