### ISSUE TITLE
fig 4 Export in sales by categories

### ISSUE THREAD

**Issue by andrasvereckei** [ceumicrodata/firms#5]
Export share in sales by categories
- Check export before and after 2017. 
Small firms export missing from 2017

Cat. definitions are in #2

" Exportarány az árbevételben, kategóriák szerint
2017-ig van meg!
vonalat megállíthatjuk az adott évben + lábjegyzet "

**Comment by korenmiklos** [comment]
See https://github.com/ceumicrodata/firms/blob/main/output/fig/export_share.png
